#include "CErrorBase.h"

CError* CError::_instance = 0;

void CError::load_defaulterrors()
{
	ADD_ERR(PAT_ERR_ALREADY_RUNNING		);
	ADD_ERR(PAT_NO_ERROR				);
	ADD_ERR(PAT_ERR_UNDEFINED			);
	ADD_ERR(PAT_ERR_ALREADY_RUNNING		);
	ADD_ERR(PAT_ERR_DOES_NOT_EXIST		);
	ADD_ERR(PAT_ERR_CREATE_WND_FAILED	);
	ADD_ERR(PAT_ERR_REGISTER_WND_FAILED	);
	ADD_ERR(PAT_ERR_OUT_OF_MEMORY		);
	ADD_ERR(PAT_ERR_INVALID_ARG			);
	ADD_ERR(PAT_ERR_DXINIT_FAILED		);
	ADD_ERR(PAT_ERR_GFX_BEGINFAILED		);
	ADD_ERR(PAT_ERR_GFX_ENDFAILED		);
}
