#pragma once
#include <string>

struct SERRORDEF
{
	SERRORDEF(unsigned int ID, char* pTxt)
		:
		m_ID(ID)
	{
		m_txt = pTxt;
	}

	unsigned int m_ID;
	std::string m_txt;
};

#define ERROR_UNDEFINED					0x04

#define ERROR_DX_NOT_INITIALIZED		0x06
#define ERROR_DX_NO_RASTER_STATE_SET	0x07
#define ERROR_DX_NO_BLEND_STATE_SET		0x08
#define ERROR_DX_NO_DEPTH_STENCIL_SET	0x08
#define ERROR_DX_NO_RENDER_TARGET_SET	0x09
#define ERROR_DX_INVALID_DIMENSIONS		0x0A
#define ERROR_DX_INVALID_HANDLE			0x0B

#define ERROR_DX_INIT_RASTER_FAILED 0x0C
#define ERROR_DX_INIT_BLEND_FAILED	0x0D
#define ERROR_DX_INIT_DEPTH_FAILED	0x0E
#define ERROR_DX_INIT_TARGET_FAILED 0x0F

#define ERROR_DX_SHADER_INVALID		0x10

static SERRORDEF ERRLIST[] = {
	{ERROR_DX_NOT_INITIALIZED,			"ERROR_DX_NOT_INITIALIZED"			},
	{ERROR_DX_NO_RASTER_STATE_SET,		"ERROR_DX_NO_RASTER_STATE_SET"		},
	{ERROR_DX_NO_BLEND_STATE_SET,		"ERROR_DX_NO_BLEND_STATE_SET"		},
	{ERROR_DX_NO_DEPTH_STENCIL_SET,		"ERROR_DX_NO_DEPTH_STENCIL_SET" 	},
	{ERROR_DX_NO_RENDER_TARGET_SET, 	"ERROR_DX_NO_RENDER_TARGET_SET"		},
	{ERROR_DX_INVALID_DIMENSIONS, 		"ERROR_DX_INVALID_DIMENSIONS"		},
	{ERROR_DX_INVALID_HANDLE,	 		"ERROR_DX_INVALID_HANDLE"			},
	{ERROR_DX_INIT_RASTER_FAILED, 		"ERROR_DX_INIT_RASTER_FAILED"		},
	{ERROR_DX_INIT_BLEND_FAILED, 		"ERROR_DX_INIT_BLEND_FAILED" 		},
	{ERROR_DX_INIT_DEPTH_FAILED,		"ERROR_DX_INIT_DEPTH_FAILED"		},
	{ERROR_DX_INIT_TARGET_FAILED,		"ERROR_DX_INIT_TARGET_FAILED"		},
	{ERROR_DX_SHADER_INVALID,			"ERROR_DX_SHADER_INVALID"			}
};					

unsigned int GetErrorID(char* txt);
const char*  GetErrorTxt(unsigned int ID);